/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Tree;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @DisplayName( "instantiate an empty tree")
    @Test
    public void test1() {
        BinarySearchTree test1 = new BinarySearchTree();
        assertNull (test1.root);
    }

    @DisplayName(" instantiate a tree with a single root node")
    @Test
    public void test2() {
        BinarySearchTree test2 = new BinarySearchTree();
        test2.add(5);
       assertNotNull (test2.root);
    }

    @DisplayName("  add a left child and right child to a single root node")
    @Test
    public void test3() {
        BinarySearchTree test3 = new BinarySearchTree();
        test3.add(5);
        test3.add(7);
        test3.add(3);
        test3.add(10);
       String expected="BinarySearchTree{root=Node{key=5, left=Node{key=3, left=null, right=null}, right=Node{key=7, left=null, right=Node{key=10, left=null, right=null}}}}" ;
        assertEquals (expected,test3.toString());
    }




}
