/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Tree;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println("Binary Tree");



        BinaryTree  binaryTree = new BinaryTree();



        binaryTree.add(55);
        binaryTree.add(99);
        binaryTree.add(22);
        binaryTree.add(10);
        binaryTree.add(11);


//        System.out.println(binaryTree.toString());
//        System.out.print("Preorder:\n");
//        System.out.println(binaryTree.Preorder());
//        System.out.print("\nInorder:\n");
//        System.out.println(binaryTree.inOrder());
//        System.out.print("\nPostorder:\n");
//        System.out.println(binaryTree.PostOrder());
//
//
//        System.out.println(binaryTree.contains(55));
//        System.out.println(binaryTree.contains(88));
//        System.out.println(binaryTree.findMaximumValue());
        binaryTree.breadthFirstTraverse(binaryTree.root);




    }
}
