/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Data.Structures;

import javax.xml.soap.Node;
public class Library {
    public boolean someLibraryMethod() {
        return true;

    }

    public static void main(String[] args) {
        Graph graph = new Graph();
        graph.addVertex("Bob");
        graph.addVertex("Alice");
        graph.addVertex("Mary");

        graph.addEdge("Bob", "Mary");
        graph.addEdge("Bob", "Alice");

        graph.removeVertex("Bob");
        graph.removeVertex("Alice");
        graph.removeVertex("Mary");
        graph.removeEdge("Bob","Alice");
        System.out.println( graph.printGraph());
//        System.out.println( graph.size());

    }

}
