/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InsertionSort;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    //>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>insertion tests<<<<<<<<<<<<<<<<<<<<<<
    @Test
    public void test1() {
        int[] input = {6, 2, 3, 4, 5, 1};
        InsertionSort array = new InsertionSort();
        array.insertionSort(input);
        int[] expected = {1, 2, 3, 4, 5, 6};
        assertArrayEquals(expected, input);
    }

    @Test
    public void test2() {
        int[] input = {8, 8, 8, 0, 0, 0};
        InsertionSort array = new InsertionSort();
        array.insertionSort(input);
        int[] expected = {0, 0, 0,8, 8, 8,8};
        assertNotEquals( expected, input);
    }
    @Test
    public void test3() {
        int[] input = {1};
        InsertionSort array = new InsertionSort();
        array.insertionSort(input);
        int[] expected = {1};
        assertArrayEquals(expected, input);
    }

    //>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>insertion tests<<<<<<<<<<<<<<<<<<<<<<
}
