/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InsertionSort;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    //>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>insertion Sort tests<<<<<<<<<<<<<<<<<<<<<<

    @Test
    public void test1() {
        int[] input = {6, 2, 3, 4, 5, 1};
        InsertionSort array = new InsertionSort();
        array.insertionSort(input);
        int[] expected = {1, 2, 3, 4, 5, 6};
        assertArrayEquals(expected, input);
    }

    @Test
    public void test2() {
        int[] input = {8, 8, 8, 0, 0, 0};
        InsertionSort array = new InsertionSort();
        array.insertionSort(input);
        int[] expected = {0, 0, 0,8, 8, 8,8};
        assertNotEquals( expected, input);
    }
    @Test
    public void test3() {
        int[] input = {1};
        InsertionSort array = new InsertionSort();
        array.insertionSort(input);
        int[] expected = {1};
        assertArrayEquals(expected, input);
    }

    //>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Merge Sort tests<<<<<<<<<<<<<<<<<<<<<<
    @Test
    public void test4(){
        int[] actual = {6, 2, 3, 4, 5, 1 };
        MergeSort mergeSort=new MergeSort();
        mergeSort.mergeSort(actual, actual.length);
        int[] expected = { 1, 2, 3, 4, 5, 6 };
        assertArrayEquals(expected, actual);
    }
    @Test
    public void test5() {
        int[] actual = {6, 5, 4, 3, 2, 1};
        MergeSort mergeSort=new MergeSort();
        mergeSort.mergeSort(actual, actual.length);
        int[] expected = {1, 2, 3, 4, 5, 6};
        assertArrayEquals(expected, actual);
    }


    @Test
    public void test6() {
        int[] actual = {6};
        MergeSort mergeSort=new MergeSort();
        mergeSort.mergeSort(actual, actual.length);
        int[] expected = {6};
        assertArrayEquals(expected, actual);
    }

    //>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Quick Sort tests<<<<<<<<<<<<<<<<<<<<<<

    @Test
    public void test7() {
        int[] actual = {5, 1, 6, 2, 3, 4};
        QuickSort quickSort=new QuickSort();
        quickSort.quickSort(actual,0,actual.length-1);

        int[] expected = {1, 2, 3, 4, 5, 6};
        assertArrayEquals(expected, actual);
    }
    @Test
    public void test8() {
        int[] actual = {-5, 1, -6, -2, 3, 4};
        QuickSort quickSort=new QuickSort();
        quickSort.quickSort(actual,0,actual.length-1);
        int[] expected = {-6, -5, -2, 1, 3, 4};
        assertArrayEquals(expected, actual);
    }

    @Test
    public void test9() {
        int[] actual = {2};
        QuickSort quickSort=new QuickSort();
        quickSort.quickSort(actual,0,actual.length-1);
        int[] expected = {2};
        assertArrayEquals(expected, actual);
    }
}
