/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HashTable;

import java.io.UnsupportedEncodingException;

public class Library {


    public static void main(String[] args) throws UnsupportedEncodingException {

        HashTable table = new HashTable();

        table.add("bayan","engineer");
        table.add("aya","graphic design");
        table.add("tala","teacher");
        table.add("rana","kids teacher");
        System.out.println(table.toString());
        System.out.println(table.contains("rana"));
        System.out.println(table.hash("Elephant"));



        String test = "Once upon a time, there was a brave princess who...";
        RepeatedWord test2=new RepeatedWord();
        System.out.println( test2.repeatedWord(test));


    }
}
