/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Data.Structures;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    linkedList test = new linkedList();

    @Test
    public void  addNodeToTheEnd(){
        test.insert(55);
        test.append(33);
        String output=test.toString();
        String expected=" { 55 } -->  { 33 } --> NULL";
        assertEquals(expected,output);
    }
    @Test
    public void addMultipleNodeToTheEnd(){
        test.insert(55);
        test.append(33);
        test.append(22);
        String output=test.toString();
        String expected=" { 55 } -->  { 33 } -->  { 22 } --> NULL";
        assertEquals(expected,output);
    }
    @Test
    public void  insertNodeBeforeNodeLocatedInMiddle(){
        test.insert(55);
        test.append(33);
        test.insertBefore(33,22);
        String output = test.toString();
        String expected = " { 55 } -->  { 22 } -->  { 33 } -->  NULL";
        assertEquals(expected,output);
    }
    @Test public void  insertNodeBeforeFirstNode(){
        test.insert(55);
        test.append(33);
        test.insertBefore(55,22);
        String output = test.toString();
        String expected = " { 22 } -->  { 55 } -->  { 33 } -->  NULL";
        assertEquals(expected,output);
    }
    @Test
    public void  insertNodeAfterNodeLocatedInMiddle(){
        test.insert(55);
        test.append(33);
        test.append(66);
        test.insertAfter(33,22);
        String output = test.toString();
        String expected = " { 55 } -->  { 33 } -->  { 22 } -->  { 66 } -->  NULL";
        assertEquals(expected,output);
    }
    @Test
    public void  insertNodeAfterLastNode(){
        test.insert(55);
        test.append(33);
        test.insertAfter(33,22);
        String output = test.toString();
        String expected = " { 55 } -->  { 33 } -->  { 22 } -->  NULL";
        assertEquals(expected,output);
    }

    @Test
    public void append() {
        test.append(11);
        String output = test.toString();
        String expected=" { 11 } --> NULL";
        assertEquals(expected, output) ;
    }

    @Test
    public void InsertBefore() {

        test.insertBefore(11, 2);
        String output = test.toString();
        String expected=" { 2 } -->  { 11 } --> NULL";
        assertEquals(expected, output) ;
    }
    @Test
    public void insertAfter() {

        test.insertAfter(11, 5);
        String output = test.toString();
        String expected="{ 2 } -->  { 11 } -->  { 5 } --> NULL";
        assertEquals(expected, output) ;
    }

    @Test
    public void testfindNthWhenKisGraterThanTheLengthOfList() {
        test.append(45);
        test.append(78);

        int output = test.findNth(3);
        int expected = -1;
        assertEquals( expected, output);

    }
    @Test
    public void testfindNthWherekAndTheLengthOfTheListAreTheSame() {
        test.append(45);
        test.append(78);

        int output = test.findNth(3);
        int expected = -1;
        assertEquals( expected, output);
    }
    @Test
    public void testfindNthWherekisNotApositiveInteger() {
        test.append(45);
        test.append(78);

        int output = test.findNth(3);
        int expected = -1;
        assertEquals( expected, output);
    }
    @Test
    public void testfindNthWhereSizeIsOne() {
        test.insert(11);
        int output = test.findNth(0);
        int expected = 11;
        assertEquals(expected, output);
    }

    @Test
    public void testfindNthWherekisInTheMiddle() {
        test.append(45);
        test.append(78);
        test.append(30);
        test.append(12);

        int output = test.findNth(3);
        int expected = 30;
        assertEquals( expected, output);
    }

    @Test
    public void testZipLists(){
        linkedList ListOne = new linkedList();
        linkedList ListTwo = new linkedList();
        ListOne.append(22);
        ListOne.append(33);
        ListOne.append(77);

        ListTwo.append(2);
        ListTwo.append(6);
        ListTwo.append(8);
        linkedList output = linkedList.zipLists(ListOne,ListTwo);
        String expected = "{ 2 } -->  { 22 } -->  { 6 } -->  { 33 } -->  { 8 } -->  { 77 } --> NULL";
        assertEquals( expected, output);
    }

}
