/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Data.Structures;

public class Library {
    public boolean someLibraryMethod() {
        return true;

    }

    public static void main(String[] args) {

        linkedList myList = new linkedList();

//        myList.insert(65);
//        myList.insert(43);
//        myList.insert(88);
//        myList.insert(57);
//        myList.insert(90);
//        myList.insert(100);


        myList.append(11);


        myList.insertBefore(11,2);
        myList.insertAfter(11,5);



        System.out.println(myList.toString());
        System.out.println(myList.includes(100));


    }
}
