/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Data.Structures;

public class Library {
    public boolean someLibraryMethod() {
        return true;

    }

    public static void main(String[] args) {

        linkedList myList = new linkedList();

        myList.append(11);
        myList.insertBefore(11,2);
        myList.insertAfter(11,5);
        myList.insertBefore(5,3);




        System.out.println(myList.toString());
        System.out.println(myList.includes(100));
        System.out.println(myList.findNth( 2));


    }
}
